Financial-Times/origami-website

_tutorials/bower-to-npm.md

For examples: o-colors depends on math-sass; o-grid depends on sass-mq. These aren't in the @financial-times namespace

sass also depends on things in node_modules

---

.circleci/config.yml
Makefile
package-lock.json
package.json

At some point, CircleCI's browsers have stopped working with Pa11y. This PR switches back to installing Chromium via npm.
I've also switched to CircleCI config 2.1 which allows for custom commands.
Some of this is copied across from engineering progression, in which I finally got gem caching sorted. So now the builds are _super_ fast.
This is needed for the builds in #100 and #102 to pass.

Fix the Pa11y tests

---

.circleci/config.yml
_tutorials/manual-build.md

The `build-folder` flag is only ignored by the watcher
when it doesn't include the `./` for some reason. I'll
investigate this separately, but for now this fixes
the tutorial.

Fix the build-tools command

---

_components/branding.md
_layouts/default.html
_specification-v1/manifest.md
_specification-v1/sass.md

- Add brand requirements to the component spec. Link to the
`o-brand` readme for specifcs on implementation.
- Add brand to the manifest spec.
- Show `h3`s in the in-page-nav for the manifest page.
Goes hand in hand with this PR: https://github.com/Financial-Times/o-brand/pull/38

Add branding to the spec.

---

.circleci/config.yml

i think? this will mean the makefile is there when the task runs, so that failing step should work now?

Add `checkout` step to autocommit task

---

pages/home.html

This now links out to design resources, and I've condensed the developer
content and moves some into contact.

Add a design section to the home page

---

_specification-v1/manifest.md

It appears have always been used as a string, and directly after its definition of `Object` in both cases the examples show a string

Change type of `documentClasses` to a `String`

---

_specification-v1/manifest.md

* Allow the value `null` for `origamiType`
* Make `origamiCategory` only apply to `origamiType: module`
* Add a **may** for the common use of keywords as a string

Make spec changes to reflect living components

---

_specification-v1/manifest.md

The component spec and the services spec only use the word "component" to refer
to our front-end components.
The manifest spec used the word "component" to refer to services, components and
all other origami projects.
Now it doesn't!
see here: https://github.com/Financial-Times/origami/issues/149
closes #149

Replace non-component uses of "component" with "project"

---

_specification-v1/manifest.md

the manifest spec is derived from this file:
https://github.com/Financial-Times/ft-origami/blob/gh-pages/docs/syntax/origamijson.md
In that file, demosDefaults.template is marked as required, but in the example it is not included.
I believe it was a mistake caused by copying and pasting the options from the `demos` field.
In reality very few of our components include a default option for `template`, and none of
our tooling has ever relied on them doing so. 
It's certainly strange, `demosDefaults` being optional but once included it must list a default `template`??

Make the template option of demosDefaults optional

---

_specification-v1/manifest.md

This is how it used in many our components.
for example: buttons, colors, footer, forms, gallery, header etc &c &c
closes #159

Allow `demos.[].data` to be a path to a JSON file

---

_specification-v1/sass.md

A primary mixin is now implemented in all Origami maintained
components.
Primary mixin proposal:
https://github.com/Financial-Times/origami-proposals/issues/6

Add the primary mixin to the Sass spec.

---

_specification-v1/components.md

the linked spec marks `demos.[].description` as `required`, so it's a must

Change `should` to `must` for demo description

---

_data/survey/2020-04-20.json
_layouts/default.html
_posts/2020-04-20-origami-survey-results.md
assets/charts.js
assets/main.scss

I've added a blog post outlining recent survey results. I've avoided
drawing too many conclusions, and think we can update when the whole
team's had a chance to look over the results and we've discussed them
in a planning session.
The charts are a little bit scappy, I've tried to make them a bit
generic and reusable but realistically this is going to need more work.
I suggest we try to use them next time we publish survey results and
make some usability changes then.
Here's what it looks like (so you can see the charts etc, which won't load on GitHub):

Add a blog post outlining survey results

---

_components/contributing.md

The manual build workshop will not work with the latest release
of Origami Build Tools. Until we release a [workshop build tool](https://github.com/Financial-Times/origami/issues/47)
require obt v9 for the workshop.

Use origami build tools v9 for the manual build workshop.

---

_tutorials/manual-build.md

- Use origami-workshop over origami-build-tools
- Use ESM over CommonJS in example
- Mention the `$system-code` Sass variable required
by o-typography
https://github.com/Financial-Times/origami/issues/34
https://github.com/Financial-Times/origami-workshop

Update the manual build tutorial.

---

_tutorials/build-service.md

Small change to improve the performance of the tutorial page. Typically best practice is to put scripts at the bottom of the page, this is because they will block the parsing of HTML slowing down the initial render of the page. Given that this is a tutorial it makes sense to keep these in the `<head>` to keep things simple, we can then use the `defer` attribute to avoid blocking render in newer browsers.

Add defer attribute to blocking script

---

pages/components.md

origami build tools is only meant for building an origami component and not for building applications which may use origami components

Remove sentence which suggests origami build tools is for applications to use

---

_layouts/default.html

Without this change, the browsers will download the png icon first because it is listed first and as the real icon.
With this change, the png icon will only download when svg icons are not supported by the browser.

Make the svg favicon the default and all the other icons the alternatives

---

_includes/header.html

The top level heading is only the current page when on that page,
not on any subpage.
https://github.com/Financial-Times/origami-website/issues/209

Correct top level heading item use of `aria-current`.

---

_includes/header.html
_specification-v1/components.md
_specification-v1/javascript.md
_specification-v1/markup.md
_specification-v1/sass.md
_tutorials/new-component/create-a-new-component-part-1.md
_tutorials/new-component/create-a-new-component-part-2.md
_tutorials/new-component/create-a-new-component-part-3.md
_tutorials/new-component/create-a-new-component-part-5.md

Move sass, js, and markup spec under the component spec in the
url structure:
- `/spec/v1/sass/` to `/spec/v1/components/sass/`
- `/spec/v1/javascript/` to `/spec/v1/components/javascript/`
- `/spec/v1/markup/` to `/spec/v1/components/markup/`
And update the breadcrumbs in the navigation accordingly.
_This is messy code which follows our existing approach. I don't know if
there is a better way with jekyll. We may want to move away from jekyll
to something more familiar to the team in the future._
Addresses: https://github.com/Financial-Times/origami-website/issues/187

Update component spec url structure and breadcrumbs

---

_includes/footer.html

closes https://github.com/Financial-Times/origami-website/issues/109
View it here --> https://ft-origami-proposals-in-898bas.herokuapp.com/
Screenshot below:

Add link to proposals in the footer

---

_specification-v1/components.md

This section, now removed, stated:
>Component JavaScript and Sass source code should be linted.
However the JavaScript part of the spec conflicted:
>JavaScript must be linted with ESLint[...]
>Developers should stick to the Origami eslintrc config[...]
As did the Sass part:
>Sass must validate using the Origami Stylelint rules, though
>exceptions may be enabled temporarily[...]
Why Origami eslint is a should where Sasslint is a must is
a separate question.

Remove lint section of the root component specification.

---

_specification-v1/sass.md

This allows utlity components such as o-toggle to state they support all brands without having to have a needless dependency on o-brand.
@chee pointed this spec issue out here :) https://github.com/Financial-Times/o-toggle/pull/69#pullrequestreview-528495735
Fixes https://github.com/Financial-Times/origami-website/issues/282

Allow components which have no brand-specific features/design to not require a dependency on o-brand

---

_specification-v1/sass.md

This aligns our sass linting spec with our javascript linting spec which allows custom linting rules to be defined for a component.
This fixes https://github.com/Financial-Times/origami/issues/53

Allow custom stylelint rules to be defined

---

_posts/2020-12-29-newsletter.md

`undefined` was being treated as a string and rendering.

Replace `undefined` blog post `description` with `false`.

---

_specification-v1/components.md

Currently that is only `@financial-times` but may include more npm scopes
in the future. This is so tools and services may be more confident in the
contents of components, from a security point of view. If The Build
Service was required to compile any npm package a malicious component could
be released by an attacker with demos and assets hosted under the `ft.com`
domain name. A limited set of allowed scopes, owned by the FT, will
mitigate such a scenario without increasing the complexity of our
tools/services.

Require V2 components are published under a Financial Times npm scope.

---

_includes/footer.html

The default branch was renamed from master to main but we forgot to update this link when that work was completed

correct the link in the footer to edit a page

---

_specification-v1/manifest.md

We have components with no brands property such as o-date, o-autoinit, and others which have no brand logic in them at all and as such work with any brand.
We should document that this is what having no brands property means.

document what havings no `brands` property defined in origami.json means for origami spec v1

---

_layouts/email-newsletter.html

Currently code blocks may overflow and break email templates. This
commit makes it so code wraps rather than overflows the email
contianer. I went with this over scrolling overflow as we have no
code block styles for email sends and it's not obvious the blocks
can be scrolled. If we ever need to share large code blocks via
email we may want to update the styles and make overflow scroll,
but it's more likely right now we're sharing inline code blocks
or something simple like a single command or url.
before:
after:

Wrap code examples in email

---

_includes/hero-image.svg
assets/main.scss

On tablet sized viewports there is currently whitespace above and below
before
after

Scale and crop the interactive homepage svg

---

_specification-v1/components.md

Takes into account steps defined to migrate a component, e.g.
https://github.com/Financial-Times/o-brand/pull/85
Including:
- Highlights `keywords` may be set
- Updates `exports` recommendation
- Requires that `main` is not set

Update npm package management spec

---

_config.yml

The runbook is not meant to be served via the website but it seems it currently is being served -- https://origami.ft.com/RUNBOOK/
This page causes our pa11y tests to fail

Do not compile RUNBOOK.md as a page on the website

---

_specification-v1/components.md

When adding verification logic to origami-build-tools we noticed that the spec did not include this rule and we thought it should.
Suggestion to add this rule to the specification came from -- https://github.com/Financial-Times/origami-build-tools/pull/997

If no main.js exists, component must not set package.json.browser

---

_components/customisation.md
_components/initialising.md
_tutorials/bower-to-npm.md
_tutorials/build-service.md
_tutorials/manual-build.md
_tutorials/new-component/create-a-new-component-part-1.md
_tutorials/new-component/create-a-new-component-part-2.md
_tutorials/new-component/create-a-new-component-part-8.md
pages/components.md

Manual Build doesn't mean anything outside Origami. The choice is
really between the Origami Build Service or installing components with
a package manager (which requires a build step).
https://financialtimes.slack.com/archives/CSW6B2VAN/p1617986490072400
now:
before:

Drop "manual build" for "Package Manager (Bower/npm)"

---

_posts/2021-01-18-deprecating-bower-and-origami-via-npm.md
_posts/2021-07-01-origami-on-npm-and-how-to-migrate.md

- Correct heading levels.
- Use o-table.
- Delete "Plans for the future". This mentioned spec v2, when we
decided to deprecate the Origami specification. This section is
now going to be its own blog post.
- Remove the "First npm-only Origami Component" heading, this content
works nicely as an example in the "benefits" section.
- Update the Build Service guide to emphasise the Origami Build Service
URL Updater more which has had useful updates to help the migration.
- Add a section which lists the last major Bower release of each component,
for reference when updating components before migrating to the npm-only
version.

Update npm-only component migration guide.

---

_config.yml
_layouts/default.html

To make it easier for people to keep up-to-date with Origami, surface the newsletter as a feed.
Generate an Atom feed using the `jekyll-feed` plugin, which is included as part of the `github-pages` gem and runs in GitHub Pages' safe-mode.
This currently pulls entire posts through, although this behaviour can be modified so that only excerpts are used, which might be preferred for analytics.
Also, this pull-request adds three new global-config keys, unfortunately the `jekyll-feed` plugin does not search for nested configuration keys:
- `title` — Used to set the feed title, potentially usable elsewhere in the site with `site.title` (I see that `page.title` is the preferred convention atm).
- `description` — I'm not sure this comes from by default!  This is set to mirror the description used …

feat: Add an atom feed

---

pages/home.html

- The Customer Products design team have moved to figma.
- The Customer Products design team are working on design system
guidelines outside of the Origami site, which may take a design-first
approach to content and may include components outside of Origami.

Update the homepage design prompt.

---

_emails/newsletter-2021-07.html
_posts/2021-08-09-newsletter.md

Closes: https://github.com/Financial-Times/origami-website/issues/369
Too wild with the new project teaser? I didn't want to get design token / mono repo specific right now

Add July 2021 newsletter

---

_posts/2021-07-01-origami-on-npm-and-how-to-migrate.md

The user may update all imports to include the ft namespace or
may list this under `includePath`.
This change is based on discussing the steps with a user. Do we
recommend one approach over the other? I suppose adding 
`node_modules/@financial-times` to `includePath` could
result in a conflict with a 3rd-party module of the same name
but on the other hand makes the migration and including future
components a little easier.

Update npm/Sass `includePath` migration guide.
